apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: juno-agent
resources:
- daemonset.yaml
- service.yaml
images:
- name: agent
  newName: quay.io/moolen/juno
  newTag: test
